# Generated by Django 4.1.3 on 2022-12-01 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('nome', models.CharField(max_length=255)),
                ('complexidade', models.CharField(blank=True, choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='baixa', error_messages={'required': 'Por favor, selecione uma opção.'}, max_length=5)),
                ('escopo', models.CharField(max_length=255)),
                ('tempo_limite', models.DateTimeField()),
                ('entregaveis', models.CharField(max_length=255)),
                ('perfil_exigido', models.CharField(max_length=255)),
                ('atividades_desempenhadas', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
