# Generated by Django 4.1.3 on 2022-12-03 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_alter_task_complexidade_alter_task_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='perfil_exigido',
            field=models.CharField(blank=True, choices=[('não definido', 'Não definido'), ('jumior', 'Jumior'), ('pleno', 'Pleno'), ('senior', 'Senior')], default='não definido', error_messages={'required': 'Por favor, selecione uma opção.'}, max_length=100),
        ),
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('nome', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
