# Generated by Django 4.1.3 on 2022-12-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_perfil_exigido_atividades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividades',
            name='user',
        ),
        migrations.AlterField(
            model_name='task',
            name='perfil_exigido',
            field=models.CharField(blank=True, choices=[('não definido', 'Não definido'), ('junior', 'Junior'), ('pleno', 'Pleno'), ('senior', 'Senior')], default='não definido', error_messages={'required': 'Por favor, selecione uma opção.'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='tempo_limite',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
